local M = {}

function M.render_ini(profile, schema, utils)
    local lines = {}
    table.insert(lines, "[SandboxSettings]")
    table.insert(lines, "; Generated by RandomDay")
    table.insert(lines, "; RANDOMDAY_MARKER=1")
    table.insert(lines, "; RANDOMDAY_MODE=seventeen_suns_non_repeating_rotation")
    table.insert(lines, "; RANDOMDAY_ROTATION_ID=" .. tostring(profile.rotation_id or "unknown_rotation"))
    table.insert(lines, "; RANDOMDAY_RUN_ID=" .. tostring(profile.run_id or "unknown_run"))
    table.insert(lines, "; RANDOMDAY_FAMILY=" .. tostring(profile.family or "action"))
    table.insert(lines, "; RANDOMDAY_FAMILY_LABEL=" .. tostring(profile.family_label or profile.family_public_name or profile.family or "ACTION"))
    table.insert(lines, "; RANDOMDAY_DAY=" .. tostring(profile.day))
    table.insert(lines, "; RANDOMDAY_ID=" .. tostring(profile.id))
    table.insert(lines, "; RANDOMDAY_NAME=" .. tostring(profile.display_name))
    table.insert(lines, "; RANDOMDAY_LOCKED_UNTIL_DAY_17=true")
    table.insert(lines, "; RANDOMDAY_REMAINING_FAMILIES=" .. tostring(profile.remaining_families_count or 0))
    table.insert(lines, "; Profile " .. tostring(profile.family_label or profile.family or "") .. " Day " .. tostring(profile.day) .. "/17 - " .. tostring(profile.display_name))
    table.insert(lines, "; This file is regenerated by the mod. Edit profiles, not this file.")
    for _, key in ipairs(schema.key_order) do
        local value = profile.settings[key]
        if value ~= nil then
            table.insert(lines, key .. "=" .. utils.ini_literal(value))
        end
    end
    return table.concat(lines, "\n") .. "\n"
end

return M
