local builder = dofile((_G.RANDOMDAY_MOD_ROOT or _G["RandomDay_" .. "RANDOMDAY_MOD_ROOT"] or "RandomDay") .. "/Scripts/ax_profiles/profile_builder.lua")

local overrides = {
    [1] = { id="live_fire_orientation", display_name="Live Fire Orientation", experience="Action baseline combat", message_line="Weapons hot. Operations are loud but readable.", dynamic_spawns="standard_pressure", ante_up="standard", lethal_lasers="standard_safety", multipliers={EnemySpawnRate=1.15, EnemyHealthMultiplier=0.95, EnemyPlayerDamageMultiplier=0.95, PlayerXPGainMultiplier=1.10}, encounter={tier="medium", theme="baseline_crossfire", mixed_encounter_chance=0.05, mixed_encounter_budget=7, mixed_encounter_cooldown=330, allow_multi_group=true}},
    [2] = { id="open_floor_skirmish", display_name="Open Floor Skirmish", experience="Builder day with light fights", message_line="Build fast. Security is distracted, not absent.", dynamic_spawns="quiet_base_safe", ante_up="quiet", lethal_lasers="low_hazard", loot_respawn=true, bonus_perks=6, base_inventory=26, multipliers={EnemySpawnRate=1.00, PlayerXPGainMultiplier=1.15}, encounter={tier="low", theme="builder_skirmish", mixed_encounter_chance=0.02, mixed_encounter_budget=4, mixed_encounter_cooldown=660}},
    [3] = { id="pest_control_drill", display_name="Pest Control Drill", experience="Pest-heavy shooting day", message_line="Small targets. Many complaints. Bring ammo.", dynamic_spawns="biohazard_light", ante_up="biohazard", lethal_lasers="standard_safety", multipliers={EnemySpawnRate=1.25, EnemyHealthMultiplier=0.95, EnemyPlayerDamageMultiplier=0.95, ThirstSpeedMultiplier=1.10}, encounter={tier="medium", theme="pest_firefight", mixed_encounter_chance=0.10, mixed_encounter_budget=8, mixed_encounter_cooldown=360, allow_multi_group=true}},
    [4] = { id="supply_run_firefight", display_name="Supply Run Firefight", experience="Loot-rich mobile combat", message_line="The supply run is authorized. So is the firefight.", dynamic_spawns="low_pressure_loot_day", ante_up="loot", lethal_lasers="low_hazard", loot_respawn=true, bonus_perks=4, base_inventory=32, multipliers={EnemySpawnRate=1.10, PlayerXPGainMultiplier=1.25, ItemWeightMultiplier=0.85}, encounter={tier="low", theme="loot_route_skirmish", mixed_encounter_chance=0.05, mixed_encounter_budget=5, mixed_encounter_cooldown=520}},
    [5] = { id="security_contact", display_name="Security Contact", experience="Security patrols with pest clashes", message_line="Security has located the problem and misidentified you as part of it.", dynamic_spawns="security_pressure", ante_up="security", lethal_lasers="moderate_hazard", game_difficulty=2, enemy_accuracy=3, multipliers={EnemySpawnRate=1.30, EnemyHealthMultiplier=1.00, EnemyPlayerDamageMultiplier=1.05, DetectionSpeedMultiplier=1.25}, encounter={tier="high", theme="security_vs_pests", mixed_encounter_chance=0.20, mixed_encounter_budget=12, mixed_encounter_cooldown=260, allow_multi_group=true, max_active_groups=2}},
    [6] = { id="weathered_engagement", display_name="Weathered Engagement", experience="Wandering mixed threats", message_line="Forecast: contact. Visibility: negotiable.", dynamic_spawns="weather_wandering", ante_up="weather", lethal_lasers="electrical_hazard_light", multipliers={EnemySpawnRate=1.20, EnemyPlayerDamageMultiplier=1.00}, encounter={tier="medium", theme="weather_crossfire", mixed_encounter_chance=0.13, mixed_encounter_budget=9, mixed_encounter_cooldown=330}},
    [7] = { id="night_raid", display_name="Night Raid", experience="Night combat and ambushes", message_line="Night has backup. So should you.", dynamic_spawns="night_pressure", ante_up="night", lethal_lasers="night_visible_moderate", game_difficulty=2, enemy_accuracy=3, multipliers={EnemySpawnRate=1.35, EnemyHealthMultiplier=1.00, EnemyPlayerDamageMultiplier=1.05, DetectionSpeedMultiplier=1.20}, encounter={tier="high", theme="night_raid", mixed_encounter_chance=0.19, mixed_encounter_budget=12, mixed_encounter_cooldown=260, allow_multi_group=true}},
    [8] = { id="route_runner", display_name="Route Runner", experience="Fast route skirmishes", message_line="Move fast. The route is arguing back.", dynamic_spawns="speedrun_pressure", ante_up="speedrun", lethal_lasers="low_to_moderate_hazard", multipliers={EnemySpawnRate=1.40, EnemyHealthMultiplier=0.85, PlayerXPGainMultiplier=1.20}, encounter={tier="high", theme="rapid_route_skirmish", mixed_encounter_chance=0.18, mixed_encounter_budget=9, mixed_encounter_cooldown=210, allow_multi_group=true}},
    [9] = { id="ration_riot", display_name="Ration Riot", experience="Scarcity with combat bursts", message_line="Lunch is theoretical. Hostiles are practical.", dynamic_spawns="scarcity_low_frequency", ante_up="scarcity", lethal_lasers="standard_safety", game_difficulty=2, multipliers={EnemySpawnRate=1.10, HungerSpeedMultiplier=1.20, ThirstSpeedMultiplier=1.15, PlayerXPGainMultiplier=1.20}, encounter={tier="medium", theme="ration_riot", mixed_encounter_chance=0.10, mixed_encounter_budget=8, mixed_encounter_cooldown=420}},
    [10] = { id="escort_recovery", display_name="Escort Recovery", experience="Low combat recovery", message_line="Recover, escort, reload, and pretend this is a plan.", dynamic_spawns="minimum_pressure", ante_up="recovery", lethal_lasers="disabled_or_low_if_supported", loot_respawn=true, bonus_perks=8, base_inventory=30, multipliers={EnemySpawnRate=0.85, EnemyPlayerDamageMultiplier=0.80, PlayerXPGainMultiplier=1.35}, encounter={tier="very_low", theme="escort_recovery", mixed_encounter_chance=0.00, mixed_encounter_budget=2, mixed_encounter_cooldown=900, allow_multi_group=false}},
    [11] = { id="training_targets", display_name="Training Targets", experience="Predictable combat training waves", message_line="Training targets have filed a complaint with claws.", dynamic_spawns="training_targets", ante_up="training", lethal_lasers="training_hazard", loot_respawn=true, bonus_perks=12, game_difficulty=1, enemy_accuracy=1, multipliers={EnemySpawnRate=1.10, EnemyHealthMultiplier=0.80, EnemyPlayerDamageMultiplier=0.80, PlayerXPGainMultiplier=1.55}, encounter={tier="low", theme="training_targets", mixed_encounter_chance=0.05, mixed_encounter_budget=6, mixed_encounter_cooldown=520}},
    [12] = { id="black_lab_assault", display_name="Black Lab Assault", experience="Heavy mixed assault", message_line="The Black Lab reviewed your performance and selected violence.", dynamic_spawns="hard_pressure", ante_up="black_lab", lethal_lasers="high_hazard", game_difficulty=3, enemy_accuracy=4, multipliers={EnemySpawnRate=1.45, EnemyHealthMultiplier=1.05, EnemyPlayerDamageMultiplier=1.10, PlayerXPGainMultiplier=1.35}, encounter={tier="extreme", theme="black_lab_assault", mixed_encounter_chance=0.30, mixed_encounter_budget=16, mixed_encounter_cooldown=190, allow_multi_group=true, max_active_groups=3}},
    [13] = { id="extended_fireline", display_name="Extended Fireline", experience="Sustained combat attrition", message_line="The shift is long. The fireline is longer.", dynamic_spawns="slow_attrition", ante_up="attrition", lethal_lasers="standard_safety", game_difficulty=2, multipliers={EnemySpawnRate=1.15, HungerSpeedMultiplier=1.15, ThirstSpeedMultiplier=1.15, FatigueSpeedMultiplier=1.15, PlayerXPGainMultiplier=1.20}, encounter={tier="medium", theme="extended_fireline", mixed_encounter_chance=0.09, mixed_encounter_budget=8, mixed_encounter_cooldown=480}},
    [14] = { id="supply_closet_miracle", display_name="Supply Closet Miracle", experience="Relief day with light contact", message_line="Take the win. It may be bait, but it is well stocked.", dynamic_spawns="relief_day", ante_up="relief", lethal_lasers="disabled_or_low_if_supported", loot_respawn=true, bonus_perks=10, base_inventory=38, multipliers={EnemySpawnRate=0.75, PlayerXPGainMultiplier=1.45, ItemWeightMultiplier=0.80}, encounter={tier="very_low", theme="relief_none", mixed_encounter_chance=0.00, mixed_encounter_budget=2, mixed_encounter_cooldown=900}},
    [15] = { id="accuracy_audit_live", display_name="Accuracy Audit Live", experience="Precision combat pressure", message_line="They aim better today. You should use cover.", dynamic_spawns="precision_patrols", ante_up="accuracy", lethal_lasers="moderate_hazard", game_difficulty=2, enemy_accuracy=4, multipliers={EnemySpawnRate=1.25, EnemyPlayerDamageMultiplier=1.15, DetectionSpeedMultiplier=1.30, PlayerXPGainMultiplier=1.25}, encounter={tier="high", theme="precision_crossfire", mixed_encounter_chance=0.17, mixed_encounter_budget=10, mixed_encounter_cooldown=280}},
    [16] = { id="experimental_crossfire", display_name="Experimental Crossfire", experience="Chaotic mixed groups", message_line="Experimental conditions have escaped the spreadsheet.", dynamic_spawns="experimental_mixed", ante_up="experimental", lethal_lasers="weird_cycle_or_standard", game_difficulty=2, enemy_accuracy=2, multipliers={EnemySpawnRate=1.35, EnemyHealthMultiplier=1.10, EnemyPlayerDamageMultiplier=1.05, PlayerXPGainMultiplier=1.55}, encounter={tier="extreme", theme="experimental_crossfire", mixed_encounter_chance=0.28, mixed_encounter_budget=16, mixed_encounter_cooldown=210, allow_multi_group=true, max_active_groups=3}},
    [17] = { id="compliance_war_game", display_name="Compliance War Game", experience="Capstone multi-group assault", message_line="Final exam conditions. Compliance is armed.", dynamic_spawns="capstone_pressure", ante_up="capstone", lethal_lasers="overcharged_high_hazard", game_difficulty=3, enemy_accuracy=4, death_penalties=2, multipliers={EnemySpawnRate=1.55, EnemyHealthMultiplier=1.15, EnemyPlayerDamageMultiplier=1.20, PlayerXPGainMultiplier=1.75}, encounter={tier="capstone", theme="compliance_war_game", mixed_encounter_chance=0.35, mixed_encounter_budget=18, mixed_encounter_cooldown=160, allow_multi_group=true, max_active_groups=3}},
}

local pack = builder.build("action", "ACTION", overrides)
return pack
