return {
    mod_version = "0.3.13-alpha-open-world-scope",
    cycle_length_days = 17,
    canonical_key_order = {
        "GameDifficulty",
        "HardcoreMode",
        "LootRespawnEnabled",
        "PowerSocketsOffAtNight",
        "DayNightCycleState",
        "DayNightCycleSpeedMultiplier",
        "WeatherFrequency",
        "SinkRefillRate",
        "FoodSpoilSpeedMultiplier",
        "RefrigerationEffectivenessMultiplier",
        "StorageByTag",
        "StructuralSupportLimit",
        "BridgeSupports",
        "HomeWorlds",
        "TaintedSinkWater",
        "RadiationDealsDamage",
        "InvisibleRadiation",
        "EnemySpawnRate",
        "EnemyHealthMultiplier",
        "EnemyPlayerDamageMultiplier",
        "EnemyDeployableDamageMultiplier",
        "DetectionSpeedMultiplier",
        "EnemyAccuracy",
        "DamageToAlliesMultiplier",
        "HungerSpeedMultiplier",
        "ThirstSpeedMultiplier",
        "FatigueSpeedMultiplier",
        "ContinenceSpeedMultiplier",
        "BonusPerkPoints",
        "PlayerXPGainMultiplier",
        "ItemStackSizeMultiplier",
        "ItemWeightMultiplier",
        "ItemDurabilityMultiplier",
        "DurabilityLossOnDeathMultiplier",
        "ShowDeathMessages",
        "AllowRecipeSharing",
        "AllowPagers",
        "AllowTransmog",
        "DisableResearchMinigame",
        "DeathPenalties",
        "FirstTimeStartingWeapon",
        "HostAccessPlayerCorpses",
        "AllowCharacterReset",
        "BaseInventorySize",
        "PlayerFurnitureDestruction",
        "AllowIronMode",
    },
    fixed_rules = {
        HardcoreMode = false,
        AllowIronMode = false,
        StructuralSupportLimit = 0,
        BridgeSupports = 0,
        AllowRecipeSharing = true,
        AllowTransmog = true,
        ShowDeathMessages = true,
        HostAccessPlayerCorpses = true,
        AllowCharacterReset = true,
    },
    profiles = {
        {
            day = 1,
            id = "mostly_normal_allegedly",
            display_name = "Mostly Normal, Allegedly",
            experience = "Standard public baseline",
            message_line = "The facility is operating within acceptable levels of denial.",
            encounter = {
                profile = "mostly_normal_allegedly",
                tier = "low",
                theme = "baseline_walkers",
                allow_multi_group = false,
                max_active_groups = 1,
                special_event_chance = 2,
                mixed_encounter_chance = 0.02,
                mixed_encounter_budget = 6,
                mixed_encounter_cooldown = 360,
                description = "Low baseline wandering pressure. Rare mixed event.",
            },
            settings = {
                GameDifficulty = 1,
                HardcoreMode = false,
                LootRespawnEnabled = false,
                PowerSocketsOffAtNight = true,
                DayNightCycleState = 0,
                DayNightCycleSpeedMultiplier = 1.0,
                WeatherFrequency = 3,
                SinkRefillRate = 1.0,
                FoodSpoilSpeedMultiplier = 1.0,
                RefrigerationEffectivenessMultiplier = 1.0,
                StorageByTag = true,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = false,
                RadiationDealsDamage = true,
                InvisibleRadiation = false,
                EnemySpawnRate = 1.0,
                EnemyHealthMultiplier = 1.0,
                EnemyPlayerDamageMultiplier = 1.0,
                EnemyDeployableDamageMultiplier = 1.0,
                DetectionSpeedMultiplier = 1.0,
                EnemyAccuracy = 2,
                DamageToAlliesMultiplier = 0.25,
                HungerSpeedMultiplier = 1.0,
                ThirstSpeedMultiplier = 1.0,
                FatigueSpeedMultiplier = 1.0,
                ContinenceSpeedMultiplier = 1.0,
                BonusPerkPoints = 0,
                PlayerXPGainMultiplier = 1.0,
                ItemStackSizeMultiplier = 2.0,
                ItemWeightMultiplier = 1.0,
                ItemDurabilityMultiplier = 1.5,
                DurabilityLossOnDeathMultiplier = 0.25,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = false,
                DeathPenalties = 1,
                FirstTimeStartingWeapon = 0,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 12,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "standard_pressure",
                lethal_lasers = "standard_safety",
                encounter_director = "mostly_normal_allegedly",
                ante_up = "standard",
            },
        },
        {
            day = 2,
            id = "open_floor_plan_authorization",
            display_name = "Open Floor Plan Authorization",
            experience = "Builder/logistics day",
            message_line = "Structural review has been replaced with optimism and a clipboard.",
            encounter = {
                profile = "open_floor_plan_authorization",
                tier = "very_low",
                theme = "quiet_base",
                allow_multi_group = false,
                max_active_groups = 1,
                special_event_chance = 0,
                mixed_encounter_chance = 0.0,
                mixed_encounter_budget = 3,
                mixed_encounter_cooldown = 720,
                description = "Builder/logistics day. Assault pressure suppressed.",
            },
            settings = {
                GameDifficulty = 1,
                HardcoreMode = false,
                LootRespawnEnabled = true,
                PowerSocketsOffAtNight = false,
                DayNightCycleState = 0,
                DayNightCycleSpeedMultiplier = 0.9,
                WeatherFrequency = 2,
                SinkRefillRate = 2.0,
                FoodSpoilSpeedMultiplier = 0.75,
                RefrigerationEffectivenessMultiplier = 1.5,
                StorageByTag = false,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = false,
                RadiationDealsDamage = true,
                InvisibleRadiation = false,
                EnemySpawnRate = 0.65,
                EnemyHealthMultiplier = 0.85,
                EnemyPlayerDamageMultiplier = 0.65,
                EnemyDeployableDamageMultiplier = 0.1,
                DetectionSpeedMultiplier = 0.65,
                EnemyAccuracy = 1,
                DamageToAlliesMultiplier = 0.0,
                HungerSpeedMultiplier = 0.65,
                ThirstSpeedMultiplier = 0.65,
                FatigueSpeedMultiplier = 0.65,
                ContinenceSpeedMultiplier = 0.65,
                BonusPerkPoints = 5,
                PlayerXPGainMultiplier = 1.25,
                ItemStackSizeMultiplier = 8.0,
                ItemWeightMultiplier = 0.55,
                ItemDurabilityMultiplier = 4.0,
                DurabilityLossOnDeathMultiplier = 0.05,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = false,
                DeathPenalties = 0,
                FirstTimeStartingWeapon = 2,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 24,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "quiet_base_safe",
                lethal_lasers = "low_hazard",
                encounter_director = "open_floor_plan_authorization",
                ante_up = "quiet",
            },
        },
        {
            day = 3,
            id = "questionable_drinking_water",
            display_name = "Questionable Drinking Water",
            experience = "Hydration and sanitation pressure",
            message_line = "Hydration is available. Legal recommends no further discussion.",
            encounter = {
                profile = "questionable_drinking_water",
                tier = "medium",
                theme = "pests_contamination",
                allow_multi_group = true,
                max_active_groups = 2,
                special_event_chance = 8,
                mixed_encounter_chance = 0.08,
                mixed_encounter_budget = 7,
                mixed_encounter_cooldown = 420,
                description = "Biohazard/pest pressure with light mixed encounters.",
            },
            settings = {
                GameDifficulty = 2,
                HardcoreMode = false,
                LootRespawnEnabled = false,
                PowerSocketsOffAtNight = true,
                DayNightCycleState = 0,
                DayNightCycleSpeedMultiplier = 1.0,
                WeatherFrequency = 3,
                SinkRefillRate = 0.25,
                FoodSpoilSpeedMultiplier = 1.25,
                RefrigerationEffectivenessMultiplier = 0.75,
                StorageByTag = true,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = true,
                RadiationDealsDamage = true,
                InvisibleRadiation = false,
                EnemySpawnRate = 1.0,
                EnemyHealthMultiplier = 1.05,
                EnemyPlayerDamageMultiplier = 1.05,
                EnemyDeployableDamageMultiplier = 0.9,
                DetectionSpeedMultiplier = 1.0,
                EnemyAccuracy = 2,
                DamageToAlliesMultiplier = 0.25,
                HungerSpeedMultiplier = 1.2,
                ThirstSpeedMultiplier = 1.75,
                FatigueSpeedMultiplier = 1.1,
                ContinenceSpeedMultiplier = 1.45,
                BonusPerkPoints = 0,
                PlayerXPGainMultiplier = 1.1,
                ItemStackSizeMultiplier = 2.0,
                ItemWeightMultiplier = 1.0,
                ItemDurabilityMultiplier = 1.25,
                DurabilityLossOnDeathMultiplier = 0.25,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = false,
                DeathPenalties = 1,
                FirstTimeStartingWeapon = 0,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 12,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "biohazard_light",
                lethal_lasers = "standard_safety",
                encounter_director = "questionable_drinking_water",
                ante_up = "biohazard",
            },
        },
        {
            day = 4,
            id = "inventory_expansion_memo",
            display_name = "Inventory Expansion Memo",
            experience = "High loot and transport utility",
            message_line = "Storage standards have been relaxed due to drawer fatigue.",
            encounter = {
                profile = "inventory_expansion_memo",
                tier = "low",
                theme = "opportunist_patrols",
                allow_multi_group = false,
                max_active_groups = 1,
                special_event_chance = 2,
                mixed_encounter_chance = 0.03,
                mixed_encounter_budget = 4,
                mixed_encounter_cooldown = 600,
                description = "Low-pressure loot day with occasional opportunists.",
            },
            settings = {
                GameDifficulty = 1,
                HardcoreMode = false,
                LootRespawnEnabled = true,
                PowerSocketsOffAtNight = false,
                DayNightCycleState = 0,
                DayNightCycleSpeedMultiplier = 1.0,
                WeatherFrequency = 2,
                SinkRefillRate = 2.5,
                FoodSpoilSpeedMultiplier = 0.6,
                RefrigerationEffectivenessMultiplier = 1.5,
                StorageByTag = false,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = false,
                RadiationDealsDamage = true,
                InvisibleRadiation = false,
                EnemySpawnRate = 0.8,
                EnemyHealthMultiplier = 0.9,
                EnemyPlayerDamageMultiplier = 0.8,
                EnemyDeployableDamageMultiplier = 0.5,
                DetectionSpeedMultiplier = 0.8,
                EnemyAccuracy = 1,
                DamageToAlliesMultiplier = 0.25,
                HungerSpeedMultiplier = 0.75,
                ThirstSpeedMultiplier = 0.75,
                FatigueSpeedMultiplier = 0.75,
                ContinenceSpeedMultiplier = 0.75,
                BonusPerkPoints = 3,
                PlayerXPGainMultiplier = 1.15,
                ItemStackSizeMultiplier = 14.0,
                ItemWeightMultiplier = 0.35,
                ItemDurabilityMultiplier = 2.5,
                DurabilityLossOnDeathMultiplier = 0.05,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = false,
                DeathPenalties = 0,
                FirstTimeStartingWeapon = 6,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 30,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "low_pressure_loot_day",
                lethal_lasers = "low_hazard",
                encounter_director = "inventory_expansion_memo",
                ante_up = "loot",
            },
        },
        {
            day = 5,
            id = "security_heard_something",
            display_name = "Security Heard Something",
            experience = "Detection/accuracy pressure",
            message_line = "Security response times have improved. Unfortunately, so has security.",
            encounter = {
                profile = "security_heard_something",
                tier = "high",
                theme = "security_vs_pests",
                allow_multi_group = true,
                max_active_groups = 2,
                special_event_chance = 14,
                mixed_encounter_chance = 0.15,
                mixed_encounter_budget = 10,
                mixed_encounter_cooldown = 300,
                description = "Security pressure with pest/portal interference.",
            },
            settings = {
                GameDifficulty = 2,
                HardcoreMode = false,
                LootRespawnEnabled = false,
                PowerSocketsOffAtNight = true,
                DayNightCycleState = 0,
                DayNightCycleSpeedMultiplier = 1.0,
                WeatherFrequency = 2,
                SinkRefillRate = 1.0,
                FoodSpoilSpeedMultiplier = 1.0,
                RefrigerationEffectivenessMultiplier = 1.0,
                StorageByTag = true,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = false,
                RadiationDealsDamage = true,
                InvisibleRadiation = false,
                EnemySpawnRate = 1.35,
                EnemyHealthMultiplier = 1.1,
                EnemyPlayerDamageMultiplier = 1.2,
                EnemyDeployableDamageMultiplier = 1.0,
                DetectionSpeedMultiplier = 1.85,
                EnemyAccuracy = 4,
                DamageToAlliesMultiplier = 0.1,
                HungerSpeedMultiplier = 1.0,
                ThirstSpeedMultiplier = 1.0,
                FatigueSpeedMultiplier = 1.15,
                ContinenceSpeedMultiplier = 1.0,
                BonusPerkPoints = 0,
                PlayerXPGainMultiplier = 1.2,
                ItemStackSizeMultiplier = 2.0,
                ItemWeightMultiplier = 1.0,
                ItemDurabilityMultiplier = 1.25,
                DurabilityLossOnDeathMultiplier = 0.3,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = false,
                DeathPenalties = 2,
                FirstTimeStartingWeapon = 4,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 12,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "security_pressure",
                lethal_lasers = "moderate_hazard",
                encounter_director = "security_heard_something",
                ante_up = "security",
            },
        },
        {
            day = 6,
            id = "weather_department_apology",
            display_name = "Weather Department Apology",
            experience = "Weather and survival disturbance",
            message_line = "Atmospheric conditions have been revised by someone with clipboard authority.",
            encounter = {
                profile = "weather_department_apology",
                tier = "medium",
                theme = "weather_intrusion",
                allow_multi_group = true,
                max_active_groups = 2,
                special_event_chance = 10,
                mixed_encounter_chance = 0.1,
                mixed_encounter_budget = 8,
                mixed_encounter_cooldown = 360,
                description = "Wandering portal/weather disruption.",
            },
            settings = {
                GameDifficulty = 1,
                HardcoreMode = false,
                LootRespawnEnabled = false,
                PowerSocketsOffAtNight = true,
                DayNightCycleState = 0,
                DayNightCycleSpeedMultiplier = 1.25,
                WeatherFrequency = 5,
                SinkRefillRate = 0.75,
                FoodSpoilSpeedMultiplier = 1.25,
                RefrigerationEffectivenessMultiplier = 0.8,
                StorageByTag = true,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = false,
                RadiationDealsDamage = true,
                InvisibleRadiation = false,
                EnemySpawnRate = 1.05,
                EnemyHealthMultiplier = 1.0,
                EnemyPlayerDamageMultiplier = 1.0,
                EnemyDeployableDamageMultiplier = 1.0,
                DetectionSpeedMultiplier = 1.05,
                EnemyAccuracy = 2,
                DamageToAlliesMultiplier = 0.25,
                HungerSpeedMultiplier = 1.1,
                ThirstSpeedMultiplier = 1.35,
                FatigueSpeedMultiplier = 1.1,
                ContinenceSpeedMultiplier = 1.0,
                BonusPerkPoints = 0,
                PlayerXPGainMultiplier = 1.0,
                ItemStackSizeMultiplier = 2.0,
                ItemWeightMultiplier = 1.0,
                ItemDurabilityMultiplier = 1.1,
                DurabilityLossOnDeathMultiplier = 0.25,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = false,
                DeathPenalties = 1,
                FirstTimeStartingWeapon = 0,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 12,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "weather_wandering",
                lethal_lasers = "electrical_hazard_light",
                encounter_director = "weather_department_apology",
                ante_up = "weather",
            },
        },
        {
            day = 7,
            id = "night_shift_with_benefits",
            display_name = "Night Shift With Benefits",
            experience = "Always-night operations",
            message_line = "The night shift has been granted additional night. Benefits remain theoretical.",
            encounter = {
                profile = "night_shift_with_benefits",
                tier = "high",
                theme = "night_ambush",
                allow_multi_group = true,
                max_active_groups = 2,
                special_event_chance = 16,
                mixed_encounter_chance = 0.16,
                mixed_encounter_budget = 10,
                mixed_encounter_cooldown = 300,
                description = "Night ambushes and mixed threats.",
            },
            settings = {
                GameDifficulty = 2,
                HardcoreMode = false,
                LootRespawnEnabled = false,
                PowerSocketsOffAtNight = false,
                DayNightCycleState = 2,
                DayNightCycleSpeedMultiplier = 1.0,
                WeatherFrequency = 4,
                SinkRefillRate = 1.0,
                FoodSpoilSpeedMultiplier = 1.0,
                RefrigerationEffectivenessMultiplier = 1.0,
                StorageByTag = true,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = false,
                RadiationDealsDamage = true,
                InvisibleRadiation = false,
                EnemySpawnRate = 1.45,
                EnemyHealthMultiplier = 1.1,
                EnemyPlayerDamageMultiplier = 1.15,
                EnemyDeployableDamageMultiplier = 1.0,
                DetectionSpeedMultiplier = 1.55,
                EnemyAccuracy = 3,
                DamageToAlliesMultiplier = 0.25,
                HungerSpeedMultiplier = 0.95,
                ThirstSpeedMultiplier = 0.95,
                FatigueSpeedMultiplier = 1.35,
                ContinenceSpeedMultiplier = 0.95,
                BonusPerkPoints = 0,
                PlayerXPGainMultiplier = 1.25,
                ItemStackSizeMultiplier = 3.0,
                ItemWeightMultiplier = 0.85,
                ItemDurabilityMultiplier = 1.5,
                DurabilityLossOnDeathMultiplier = 0.2,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = false,
                DeathPenalties = 1,
                FirstTimeStartingWeapon = 5,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 16,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "night_pressure",
                lethal_lasers = "night_visible_moderate",
                encounter_director = "night_shift_with_benefits",
                ante_up = "night",
            },
        },
        {
            day = 8,
            id = "clock_department_incident",
            display_name = "Clock Department Incident",
            experience = "Fast-cycle route pressure",
            message_line = "Timekeeping has been optimized by personnel who were not asked.",
            encounter = {
                profile = "clock_department_incident",
                tier = "high",
                theme = "rapid_route_skirmish",
                allow_multi_group = true,
                max_active_groups = 2,
                special_event_chance = 14,
                mixed_encounter_chance = 0.14,
                mixed_encounter_budget = 8,
                mixed_encounter_cooldown = 240,
                description = "Fast route pressure with short cooldowns.",
            },
            settings = {
                GameDifficulty = 1,
                HardcoreMode = false,
                LootRespawnEnabled = false,
                PowerSocketsOffAtNight = true,
                DayNightCycleState = 0,
                DayNightCycleSpeedMultiplier = 3.0,
                WeatherFrequency = 3,
                SinkRefillRate = 1.5,
                FoodSpoilSpeedMultiplier = 0.9,
                RefrigerationEffectivenessMultiplier = 1.1,
                StorageByTag = true,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = false,
                RadiationDealsDamage = true,
                InvisibleRadiation = false,
                EnemySpawnRate = 1.25,
                EnemyHealthMultiplier = 0.8,
                EnemyPlayerDamageMultiplier = 1.0,
                EnemyDeployableDamageMultiplier = 0.8,
                DetectionSpeedMultiplier = 1.35,
                EnemyAccuracy = 2,
                DamageToAlliesMultiplier = 0.25,
                HungerSpeedMultiplier = 0.7,
                ThirstSpeedMultiplier = 0.7,
                FatigueSpeedMultiplier = 0.7,
                ContinenceSpeedMultiplier = 0.7,
                BonusPerkPoints = 0,
                PlayerXPGainMultiplier = 1.35,
                ItemStackSizeMultiplier = 4.0,
                ItemWeightMultiplier = 0.8,
                ItemDurabilityMultiplier = 1.25,
                DurabilityLossOnDeathMultiplier = 0.15,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = true,
                DeathPenalties = 0,
                FirstTimeStartingWeapon = 6,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 18,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "speedrun_pressure",
                lethal_lasers = "low_to_moderate_hazard",
                encounter_director = "clock_department_incident",
                ante_up = "speedrun",
            },
        },
        {
            day = 9,
            id = "lab_rations_committee",
            display_name = "Lab Rations Committee",
            experience = "Scarcity and logistics hardship",
            message_line = "Lunch has been reclassified as an optional morale experiment.",
            encounter = {
                profile = "lab_rations_committee",
                tier = "medium",
                theme = "scarcity_raids",
                allow_multi_group = true,
                max_active_groups = 2,
                special_event_chance = 8,
                mixed_encounter_chance = 0.07,
                mixed_encounter_budget = 7,
                mixed_encounter_cooldown = 480,
                description = "Sparse but punishing attrition raids.",
            },
            settings = {
                GameDifficulty = 2,
                HardcoreMode = false,
                LootRespawnEnabled = false,
                PowerSocketsOffAtNight = true,
                DayNightCycleState = 0,
                DayNightCycleSpeedMultiplier = 1.0,
                WeatherFrequency = 2,
                SinkRefillRate = 0.5,
                FoodSpoilSpeedMultiplier = 2.0,
                RefrigerationEffectivenessMultiplier = 0.5,
                StorageByTag = true,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = true,
                RadiationDealsDamage = true,
                InvisibleRadiation = false,
                EnemySpawnRate = 0.95,
                EnemyHealthMultiplier = 1.15,
                EnemyPlayerDamageMultiplier = 1.1,
                EnemyDeployableDamageMultiplier = 1.0,
                DetectionSpeedMultiplier = 1.0,
                EnemyAccuracy = 2,
                DamageToAlliesMultiplier = 0.25,
                HungerSpeedMultiplier = 1.6,
                ThirstSpeedMultiplier = 1.5,
                FatigueSpeedMultiplier = 1.3,
                ContinenceSpeedMultiplier = 1.25,
                BonusPerkPoints = 0,
                PlayerXPGainMultiplier = 0.9,
                ItemStackSizeMultiplier = 1.0,
                ItemWeightMultiplier = 1.45,
                ItemDurabilityMultiplier = 0.75,
                DurabilityLossOnDeathMultiplier = 0.35,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = false,
                DeathPenalties = 2,
                FirstTimeStartingWeapon = 0,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 10,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "scarcity_low_frequency",
                lethal_lasers = "standard_safety",
                encounter_director = "lab_rations_committee",
                ante_up = "scarcity",
            },
        },
        {
            day = 10,
            id = "bring_your_scientist_to_work_day",
            display_name = "Bring Your Scientist to Work Day",
            experience = "Low-pressure recovery/exploration day",
            message_line = "Please escort fragile personnel, ideas, and morale with appropriate care.",
            encounter = {
                profile = "bring_your_scientist_to_work_day",
                tier = "very_low",
                theme = "recovery_none",
                allow_multi_group = false,
                max_active_groups = 1,
                special_event_chance = 0,
                mixed_encounter_chance = 0.0,
                mixed_encounter_budget = 2,
                mixed_encounter_cooldown = 900,
                description = "Recovery/exploration day. Assault suppressed.",
            },
            settings = {
                GameDifficulty = 1,
                HardcoreMode = false,
                LootRespawnEnabled = true,
                PowerSocketsOffAtNight = false,
                DayNightCycleState = 0,
                DayNightCycleSpeedMultiplier = 0.85,
                WeatherFrequency = 1,
                SinkRefillRate = 3.0,
                FoodSpoilSpeedMultiplier = 0.4,
                RefrigerationEffectivenessMultiplier = 1.8,
                StorageByTag = false,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = false,
                RadiationDealsDamage = false,
                InvisibleRadiation = false,
                EnemySpawnRate = 0.5,
                EnemyHealthMultiplier = 0.75,
                EnemyPlayerDamageMultiplier = 0.35,
                EnemyDeployableDamageMultiplier = 0.1,
                DetectionSpeedMultiplier = 0.45,
                EnemyAccuracy = 0,
                DamageToAlliesMultiplier = 0.0,
                HungerSpeedMultiplier = 0.45,
                ThirstSpeedMultiplier = 0.45,
                FatigueSpeedMultiplier = 0.45,
                ContinenceSpeedMultiplier = 0.45,
                BonusPerkPoints = 8,
                PlayerXPGainMultiplier = 1.5,
                ItemStackSizeMultiplier = 10.0,
                ItemWeightMultiplier = 0.45,
                ItemDurabilityMultiplier = 3.0,
                DurabilityLossOnDeathMultiplier = 0.0,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = false,
                DeathPenalties = 0,
                FirstTimeStartingWeapon = 2,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 28,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "minimum_pressure",
                lethal_lasers = "disabled_or_low_if_supported",
                encounter_director = "bring_your_scientist_to_work_day",
                ante_up = "recovery",
            },
        },
        {
            day = 11,
            id = "mandatory_safety_training",
            display_name = "Mandatory Safety Training",
            experience = "Training and progression day",
            message_line = "Danger has been reduced to improve learning outcomes. Results may vary.",
            encounter = {
                profile = "mandatory_safety_training",
                tier = "low",
                theme = "training_targets",
                allow_multi_group = false,
                max_active_groups = 1,
                special_event_chance = 3,
                mixed_encounter_chance = 0.03,
                mixed_encounter_budget = 5,
                mixed_encounter_cooldown = 600,
                description = "Predictable low-risk training pressure.",
            },
            settings = {
                GameDifficulty = 1,
                HardcoreMode = false,
                LootRespawnEnabled = true,
                PowerSocketsOffAtNight = false,
                DayNightCycleState = 0,
                DayNightCycleSpeedMultiplier = 1.15,
                WeatherFrequency = 2,
                SinkRefillRate = 2.0,
                FoodSpoilSpeedMultiplier = 0.8,
                RefrigerationEffectivenessMultiplier = 1.3,
                StorageByTag = true,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = false,
                RadiationDealsDamage = true,
                InvisibleRadiation = false,
                EnemySpawnRate = 1.0,
                EnemyHealthMultiplier = 0.85,
                EnemyPlayerDamageMultiplier = 0.65,
                EnemyDeployableDamageMultiplier = 0.4,
                DetectionSpeedMultiplier = 0.85,
                EnemyAccuracy = 1,
                DamageToAlliesMultiplier = 0.25,
                HungerSpeedMultiplier = 0.8,
                ThirstSpeedMultiplier = 0.8,
                FatigueSpeedMultiplier = 0.8,
                ContinenceSpeedMultiplier = 0.8,
                BonusPerkPoints = 12,
                PlayerXPGainMultiplier = 2.0,
                ItemStackSizeMultiplier = 5.0,
                ItemWeightMultiplier = 0.7,
                ItemDurabilityMultiplier = 2.25,
                DurabilityLossOnDeathMultiplier = 0.0,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = true,
                DeathPenalties = 0,
                FirstTimeStartingWeapon = 6,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 24,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "training_targets",
                lethal_lasers = "training_hazard",
                encounter_director = "mandatory_safety_training",
                ante_up = "training",
            },
        },
        {
            day = 12,
            id = "black_lab_performance_review",
            display_name = "Black Lab Performance Review",
            experience = "High-pressure combat day",
            message_line = "The facility has reviewed your progress and chosen disappointment.",
            encounter = {
                profile = "black_lab_performance_review",
                tier = "extreme",
                theme = "black_lab_assault",
                allow_multi_group = true,
                max_active_groups = 3,
                special_event_chance = 22,
                mixed_encounter_chance = 0.24,
                mixed_encounter_budget = 14,
                mixed_encounter_cooldown = 210,
                description = "Heavy mixed assault pressure.",
            },
            settings = {
                GameDifficulty = 3,
                HardcoreMode = false,
                LootRespawnEnabled = false,
                PowerSocketsOffAtNight = true,
                DayNightCycleState = 0,
                DayNightCycleSpeedMultiplier = 1.0,
                WeatherFrequency = 3,
                SinkRefillRate = 0.75,
                FoodSpoilSpeedMultiplier = 1.15,
                RefrigerationEffectivenessMultiplier = 0.85,
                StorageByTag = true,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = true,
                RadiationDealsDamage = true,
                InvisibleRadiation = false,
                EnemySpawnRate = 1.8,
                EnemyHealthMultiplier = 1.65,
                EnemyPlayerDamageMultiplier = 1.75,
                EnemyDeployableDamageMultiplier = 1.4,
                DetectionSpeedMultiplier = 1.75,
                EnemyAccuracy = 4,
                DamageToAlliesMultiplier = 0.15,
                HungerSpeedMultiplier = 1.15,
                ThirstSpeedMultiplier = 1.15,
                FatigueSpeedMultiplier = 1.15,
                ContinenceSpeedMultiplier = 1.0,
                BonusPerkPoints = 0,
                PlayerXPGainMultiplier = 1.35,
                ItemStackSizeMultiplier = 2.0,
                ItemWeightMultiplier = 1.1,
                ItemDurabilityMultiplier = 1.1,
                DurabilityLossOnDeathMultiplier = 0.4,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = false,
                DeathPenalties = 3,
                FirstTimeStartingWeapon = 1,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 12,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "hard_pressure",
                lethal_lasers = "high_hazard",
                encounter_director = "black_lab_performance_review",
                ante_up = "black_lab",
            },
        },
        {
            day = 13,
            id = "extended_shift_survival_trial",
            display_name = "Extended Shift Survival Trial",
            experience = "Slow attrition survival day",
            message_line = "Your shift has been lengthened to promote resilience and quiet resentment.",
            encounter = {
                profile = "extended_shift_survival_trial",
                tier = "medium",
                theme = "slow_attrition",
                allow_multi_group = true,
                max_active_groups = 2,
                special_event_chance = 7,
                mixed_encounter_chance = 0.06,
                mixed_encounter_budget = 7,
                mixed_encounter_cooldown = 540,
                description = "Slow attrition with sustained pressure.",
            },
            settings = {
                GameDifficulty = 2,
                HardcoreMode = false,
                LootRespawnEnabled = false,
                PowerSocketsOffAtNight = true,
                DayNightCycleState = 0,
                DayNightCycleSpeedMultiplier = 0.3,
                WeatherFrequency = 2,
                SinkRefillRate = 0.35,
                FoodSpoilSpeedMultiplier = 1.8,
                RefrigerationEffectivenessMultiplier = 0.65,
                StorageByTag = true,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = true,
                RadiationDealsDamage = true,
                InvisibleRadiation = false,
                EnemySpawnRate = 0.85,
                EnemyHealthMultiplier = 1.25,
                EnemyPlayerDamageMultiplier = 1.2,
                EnemyDeployableDamageMultiplier = 0.9,
                DetectionSpeedMultiplier = 1.0,
                EnemyAccuracy = 2,
                DamageToAlliesMultiplier = 0.25,
                HungerSpeedMultiplier = 1.75,
                ThirstSpeedMultiplier = 1.75,
                FatigueSpeedMultiplier = 1.65,
                ContinenceSpeedMultiplier = 1.35,
                BonusPerkPoints = 0,
                PlayerXPGainMultiplier = 1.0,
                ItemStackSizeMultiplier = 2.0,
                ItemWeightMultiplier = 1.6,
                ItemDurabilityMultiplier = 0.9,
                DurabilityLossOnDeathMultiplier = 0.35,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = false,
                DeathPenalties = 2,
                FirstTimeStartingWeapon = 0,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 10,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "slow_attrition",
                lethal_lasers = "standard_safety",
                encounter_director = "extended_shift_survival_trial",
                ante_up = "attrition",
            },
        },
        {
            day = 14,
            id = "supply_closet_miracle",
            display_name = "Supply Closet Miracle",
            experience = "Generous recovery/logistics day",
            message_line = "A storage surplus has occurred. Please do not investigate causality.",
            encounter = {
                profile = "supply_closet_miracle",
                tier = "very_low",
                theme = "relief_none",
                allow_multi_group = false,
                max_active_groups = 1,
                special_event_chance = 0,
                mixed_encounter_chance = 0.0,
                mixed_encounter_budget = 2,
                mixed_encounter_cooldown = 900,
                description = "Relief day. Assault suppressed.",
            },
            settings = {
                GameDifficulty = 1,
                HardcoreMode = false,
                LootRespawnEnabled = true,
                PowerSocketsOffAtNight = false,
                DayNightCycleState = 0,
                DayNightCycleSpeedMultiplier = 1.0,
                WeatherFrequency = 1,
                SinkRefillRate = 5.0,
                FoodSpoilSpeedMultiplier = 0.25,
                RefrigerationEffectivenessMultiplier = 2.0,
                StorageByTag = false,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = false,
                RadiationDealsDamage = false,
                InvisibleRadiation = false,
                EnemySpawnRate = 0.6,
                EnemyHealthMultiplier = 0.8,
                EnemyPlayerDamageMultiplier = 0.5,
                EnemyDeployableDamageMultiplier = 0.1,
                DetectionSpeedMultiplier = 0.6,
                EnemyAccuracy = 0,
                DamageToAlliesMultiplier = 0.0,
                HungerSpeedMultiplier = 0.35,
                ThirstSpeedMultiplier = 0.35,
                FatigueSpeedMultiplier = 0.35,
                ContinenceSpeedMultiplier = 0.35,
                BonusPerkPoints = 10,
                PlayerXPGainMultiplier = 1.75,
                ItemStackSizeMultiplier = 20.0,
                ItemWeightMultiplier = 0.25,
                ItemDurabilityMultiplier = 6.0,
                DurabilityLossOnDeathMultiplier = 0.0,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = false,
                DeathPenalties = 0,
                FirstTimeStartingWeapon = 6,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 36,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "relief_day",
                lethal_lasers = "disabled_or_low_if_supported",
                encounter_director = "supply_closet_miracle",
                ante_up = "relief",
            },
        },
        {
            day = 15,
            id = "accuracy_audit",
            display_name = "Accuracy Audit",
            experience = "Precision enemy day",
            message_line = "Hostile entities have been reminded to aim before filing complaints.",
            encounter = {
                profile = "accuracy_audit",
                tier = "high",
                theme = "precision_patrols",
                allow_multi_group = true,
                max_active_groups = 2,
                special_event_chance = 14,
                mixed_encounter_chance = 0.13,
                mixed_encounter_budget = 8,
                mixed_encounter_cooldown = 330,
                description = "Precision patrol pressure with distractions.",
            },
            settings = {
                GameDifficulty = 2,
                HardcoreMode = false,
                LootRespawnEnabled = false,
                PowerSocketsOffAtNight = true,
                DayNightCycleState = 0,
                DayNightCycleSpeedMultiplier = 1.0,
                WeatherFrequency = 2,
                SinkRefillRate = 1.0,
                FoodSpoilSpeedMultiplier = 1.0,
                RefrigerationEffectivenessMultiplier = 1.0,
                StorageByTag = true,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = false,
                RadiationDealsDamage = true,
                InvisibleRadiation = false,
                EnemySpawnRate = 1.05,
                EnemyHealthMultiplier = 0.95,
                EnemyPlayerDamageMultiplier = 1.35,
                EnemyDeployableDamageMultiplier = 0.8,
                DetectionSpeedMultiplier = 1.35,
                EnemyAccuracy = 4,
                DamageToAlliesMultiplier = 0.0,
                HungerSpeedMultiplier = 1.0,
                ThirstSpeedMultiplier = 1.0,
                FatigueSpeedMultiplier = 1.25,
                ContinenceSpeedMultiplier = 1.0,
                BonusPerkPoints = 0,
                PlayerXPGainMultiplier = 1.2,
                ItemStackSizeMultiplier = 2.0,
                ItemWeightMultiplier = 1.0,
                ItemDurabilityMultiplier = 1.0,
                DurabilityLossOnDeathMultiplier = 0.3,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = false,
                DeathPenalties = 2,
                FirstTimeStartingWeapon = 4,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 12,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "precision_patrols",
                lethal_lasers = "moderate_hazard",
                encounter_director = "accuracy_audit",
                ante_up = "accuracy",
            },
        },
        {
            day = 16,
            id = "approved_experimental_conditions",
            display_name = "Approved Experimental Conditions",
            experience = "Extreme mixed-variable day",
            message_line = "Today's variables are approved, documented, and absolutely not understood.",
            encounter = {
                profile = "approved_experimental_conditions",
                tier = "extreme",
                theme = "experimental_mixed",
                allow_multi_group = true,
                max_active_groups = 3,
                special_event_chance = 20,
                mixed_encounter_chance = 0.22,
                mixed_encounter_budget = 14,
                mixed_encounter_cooldown = 240,
                description = "Mixed-variable chaos and high conflict chance.",
            },
            settings = {
                GameDifficulty = 2,
                HardcoreMode = false,
                LootRespawnEnabled = true,
                PowerSocketsOffAtNight = false,
                DayNightCycleState = 1,
                DayNightCycleSpeedMultiplier = 1.5,
                WeatherFrequency = 5,
                SinkRefillRate = 0.0,
                FoodSpoilSpeedMultiplier = 0.4,
                RefrigerationEffectivenessMultiplier = 2.0,
                StorageByTag = false,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = true,
                RadiationDealsDamage = true,
                InvisibleRadiation = true,
                EnemySpawnRate = 1.2,
                EnemyHealthMultiplier = 1.35,
                EnemyPlayerDamageMultiplier = 0.85,
                EnemyDeployableDamageMultiplier = 0.7,
                DetectionSpeedMultiplier = 0.5,
                EnemyAccuracy = 1,
                DamageToAlliesMultiplier = 0.0,
                HungerSpeedMultiplier = 0.8,
                ThirstSpeedMultiplier = 1.2,
                FatigueSpeedMultiplier = 0.8,
                ContinenceSpeedMultiplier = 1.2,
                BonusPerkPoints = 15,
                PlayerXPGainMultiplier = 1.9,
                ItemStackSizeMultiplier = 15.0,
                ItemWeightMultiplier = 0.2,
                ItemDurabilityMultiplier = 5.0,
                DurabilityLossOnDeathMultiplier = 0.0,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = true,
                DeathPenalties = 0,
                FirstTimeStartingWeapon = 6,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 42,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "experimental_mixed",
                lethal_lasers = "weird_cycle_or_standard",
                encounter_director = "approved_experimental_conditions",
                ante_up = "experimental",
            },
        },
        {
            day = 17,
            id = "end_of_rotation_compliance_test",
            display_name = "End-of-Rotation Compliance Test",
            experience = "Capstone pressure day",
            message_line = "Congratulations. The facility has prepared a practical exam.",
            encounter = {
                profile = "end_of_rotation_compliance_test",
                tier = "capstone",
                theme = "capstone_mixed",
                allow_multi_group = true,
                max_active_groups = 3,
                special_event_chance = 30,
                mixed_encounter_chance = 0.3,
                mixed_encounter_budget = 16,
                mixed_encounter_cooldown = 180,
                description = "Capstone mixed assault. Highest conflict chance.",
            },
            settings = {
                GameDifficulty = 3,
                HardcoreMode = false,
                LootRespawnEnabled = false,
                PowerSocketsOffAtNight = true,
                DayNightCycleState = 0,
                DayNightCycleSpeedMultiplier = 1.45,
                WeatherFrequency = 5,
                SinkRefillRate = 0.5,
                FoodSpoilSpeedMultiplier = 1.6,
                RefrigerationEffectivenessMultiplier = 0.6,
                StorageByTag = true,
                StructuralSupportLimit = 0,
                BridgeSupports = 0,
                HomeWorlds = true,
                TaintedSinkWater = true,
                RadiationDealsDamage = true,
                InvisibleRadiation = false,
                EnemySpawnRate = 2.2,
                EnemyHealthMultiplier = 2.0,
                EnemyPlayerDamageMultiplier = 2.0,
                EnemyDeployableDamageMultiplier = 2.0,
                DetectionSpeedMultiplier = 2.0,
                EnemyAccuracy = 4,
                DamageToAlliesMultiplier = 0.1,
                HungerSpeedMultiplier = 1.35,
                ThirstSpeedMultiplier = 1.35,
                FatigueSpeedMultiplier = 1.25,
                ContinenceSpeedMultiplier = 1.1,
                BonusPerkPoints = 0,
                PlayerXPGainMultiplier = 1.5,
                ItemStackSizeMultiplier = 3.0,
                ItemWeightMultiplier = 1.2,
                ItemDurabilityMultiplier = 1.0,
                DurabilityLossOnDeathMultiplier = 0.5,
                ShowDeathMessages = true,
                AllowRecipeSharing = true,
                AllowPagers = true,
                AllowTransmog = true,
                DisableResearchMinigame = false,
                DeathPenalties = 3,
                FirstTimeStartingWeapon = 0,
                HostAccessPlayerCorpses = true,
                AllowCharacterReset = true,
                BaseInventorySize = 12,
                PlayerFurnitureDestruction = false,
                AllowIronMode = false,
            },
            external_profiles = {
                dynamic_spawns = "capstone_pressure",
                lethal_lasers = "overcharged_high_hazard",
                encounter_director = "end_of_rotation_compliance_test",
                ante_up = "capstone",
            },
        },
    },
}
