local M = {}

M.by_day = {
    [1] = {
        id = "mostly_normal_allegedly",
        display_name = "Mostly Normal, Allegedly",
        tier = "low",
        theme = "baseline_walkers",
        allow_multi_group = false,
        max_active_groups = 1,
        mixed_encounter_chance = 0.02,
        special_event_chance = 2,
        mixed_encounter_budget = 6,
        mixed_encounter_cooldown = 360,
        ante_up_profile = "standard",
        description = "Low baseline wandering pressure. Rare mixed event.",
        groups = { "facility_wanderers" },
    },
    [2] = {
        id = "open_floor_plan_authorization",
        display_name = "Open Floor Plan Authorization",
        tier = "very_low",
        theme = "quiet_base",
        allow_multi_group = false,
        max_active_groups = 1,
        mixed_encounter_chance = 0.0,
        special_event_chance = 0,
        mixed_encounter_budget = 3,
        mixed_encounter_cooldown = 720,
        ante_up_profile = "quiet",
        description = "Builder/logistics day. Assault pressure suppressed.",
        groups = { "quiet_patrols" },
    },
    [3] = {
        id = "questionable_drinking_water",
        display_name = "Questionable Drinking Water",
        tier = "medium",
        theme = "pests_contamination",
        allow_multi_group = true,
        max_active_groups = 2,
        mixed_encounter_chance = 0.08,
        special_event_chance = 8,
        mixed_encounter_budget = 7,
        mixed_encounter_cooldown = 420,
        ante_up_profile = "biohazard",
        description = "Biohazard/pest pressure with light mixed encounters.",
        groups = { "pests", "contamination" },
    },
    [4] = {
        id = "inventory_expansion_memo",
        display_name = "Inventory Expansion Memo",
        tier = "low",
        theme = "opportunist_patrols",
        allow_multi_group = false,
        max_active_groups = 1,
        mixed_encounter_chance = 0.03,
        special_event_chance = 2,
        mixed_encounter_budget = 4,
        mixed_encounter_cooldown = 600,
        ante_up_profile = "loot",
        description = "Low-pressure loot day with occasional opportunists.",
        groups = { "opportunists" },
    },
    [5] = {
        id = "security_heard_something",
        display_name = "Security Heard Something",
        tier = "high",
        theme = "security_vs_pests",
        allow_multi_group = true,
        max_active_groups = 2,
        mixed_encounter_chance = 0.15,
        special_event_chance = 14,
        mixed_encounter_budget = 10,
        mixed_encounter_cooldown = 300,
        ante_up_profile = "security",
        description = "Security pressure with pest/portal interference.",
        groups = { "security", "pests", "mixed_security_pest" },
    },
    [6] = {
        id = "weather_department_apology",
        display_name = "Weather Department Apology",
        tier = "medium",
        theme = "weather_intrusion",
        allow_multi_group = true,
        max_active_groups = 2,
        mixed_encounter_chance = 0.1,
        special_event_chance = 10,
        mixed_encounter_budget = 8,
        mixed_encounter_cooldown = 360,
        ante_up_profile = "weather",
        description = "Wandering portal/weather disruption.",
        groups = { "portal", "wildlife" },
    },
    [7] = {
        id = "night_shift_with_benefits",
        display_name = "Night Shift With Benefits",
        tier = "high",
        theme = "night_ambush",
        allow_multi_group = true,
        max_active_groups = 2,
        mixed_encounter_chance = 0.16,
        special_event_chance = 16,
        mixed_encounter_budget = 10,
        mixed_encounter_cooldown = 300,
        ante_up_profile = "night",
        description = "Night ambushes and mixed threats.",
        groups = { "night_pests", "security_sweep" },
    },
    [8] = {
        id = "clock_department_incident",
        display_name = "Clock Department Incident",
        tier = "high",
        theme = "rapid_route_skirmish",
        allow_multi_group = true,
        max_active_groups = 2,
        mixed_encounter_chance = 0.14,
        special_event_chance = 14,
        mixed_encounter_budget = 8,
        mixed_encounter_cooldown = 240,
        ante_up_profile = "speedrun",
        description = "Fast route pressure with short cooldowns.",
        groups = { "rapid_pests", "rapid_order" },
    },
    [9] = {
        id = "lab_rations_committee",
        display_name = "Lab Rations Committee",
        tier = "medium",
        theme = "scarcity_raids",
        allow_multi_group = true,
        max_active_groups = 2,
        mixed_encounter_chance = 0.07,
        special_event_chance = 8,
        mixed_encounter_budget = 7,
        mixed_encounter_cooldown = 480,
        ante_up_profile = "scarcity",
        description = "Sparse but punishing attrition raids.",
        groups = { "raiders", "pests" },
    },
    [10] = {
        id = "bring_your_scientist_to_work_day",
        display_name = "Bring Your Scientist to Work Day",
        tier = "very_low",
        theme = "recovery_none",
        allow_multi_group = false,
        max_active_groups = 1,
        mixed_encounter_chance = 0.0,
        special_event_chance = 0,
        mixed_encounter_budget = 2,
        mixed_encounter_cooldown = 900,
        ante_up_profile = "recovery",
        description = "Recovery/exploration day. Assault suppressed.",
        groups = {  },
    },
    [11] = {
        id = "mandatory_safety_training",
        display_name = "Mandatory Safety Training",
        tier = "low",
        theme = "training_targets",
        allow_multi_group = false,
        max_active_groups = 1,
        mixed_encounter_chance = 0.03,
        special_event_chance = 3,
        mixed_encounter_budget = 5,
        mixed_encounter_cooldown = 600,
        ante_up_profile = "training",
        description = "Predictable low-risk training pressure.",
        groups = { "training_targets" },
    },
    [12] = {
        id = "black_lab_performance_review",
        display_name = "Black Lab Performance Review",
        tier = "extreme",
        theme = "black_lab_assault",
        allow_multi_group = true,
        max_active_groups = 3,
        mixed_encounter_chance = 0.24,
        special_event_chance = 22,
        mixed_encounter_budget = 14,
        mixed_encounter_cooldown = 210,
        ante_up_profile = "black_lab",
        description = "Heavy mixed assault pressure.",
        groups = { "order_heavy", "anteverse", "mixed_combat_zone" },
    },
    [13] = {
        id = "extended_shift_survival_trial",
        display_name = "Extended Shift Survival Trial",
        tier = "medium",
        theme = "slow_attrition",
        allow_multi_group = true,
        max_active_groups = 2,
        mixed_encounter_chance = 0.06,
        special_event_chance = 7,
        mixed_encounter_budget = 7,
        mixed_encounter_cooldown = 540,
        ante_up_profile = "attrition",
        description = "Slow attrition with sustained pressure.",
        groups = { "attrition_pests", "attrition_order" },
    },
    [14] = {
        id = "supply_closet_miracle",
        display_name = "Supply Closet Miracle",
        tier = "very_low",
        theme = "relief_none",
        allow_multi_group = false,
        max_active_groups = 1,
        mixed_encounter_chance = 0.0,
        special_event_chance = 0,
        mixed_encounter_budget = 2,
        mixed_encounter_cooldown = 900,
        ante_up_profile = "relief",
        description = "Relief day. Assault suppressed.",
        groups = {  },
    },
    [15] = {
        id = "accuracy_audit",
        display_name = "Accuracy Audit",
        tier = "high",
        theme = "precision_patrols",
        allow_multi_group = true,
        max_active_groups = 2,
        mixed_encounter_chance = 0.13,
        special_event_chance = 14,
        mixed_encounter_budget = 8,
        mixed_encounter_cooldown = 330,
        ante_up_profile = "accuracy",
        description = "Precision patrol pressure with distractions.",
        groups = { "precision_order", "security_distraction" },
    },
    [16] = {
        id = "approved_experimental_conditions",
        display_name = "Approved Experimental Conditions",
        tier = "extreme",
        theme = "experimental_mixed",
        allow_multi_group = true,
        max_active_groups = 3,
        mixed_encounter_chance = 0.22,
        special_event_chance = 20,
        mixed_encounter_budget = 14,
        mixed_encounter_cooldown = 240,
        ante_up_profile = "experimental",
        description = "Mixed-variable chaos and high conflict chance.",
        groups = { "order", "pests", "gatekeepers", "anteverse" },
    },
    [17] = {
        id = "end_of_rotation_compliance_test",
        display_name = "End-of-Rotation Compliance Test",
        tier = "capstone",
        theme = "capstone_mixed",
        allow_multi_group = true,
        max_active_groups = 3,
        mixed_encounter_chance = 0.3,
        special_event_chance = 30,
        mixed_encounter_budget = 16,
        mixed_encounter_cooldown = 180,
        ante_up_profile = "capstone",
        description = "Capstone mixed assault. Highest conflict chance.",
        groups = { "capstone_order", "capstone_anteverse", "capstone_mixed" },
    },
}

function M.get(profile)
    local day = type(profile) == "table" and tonumber(profile.day) or tonumber(profile)
    return M.by_day[day]
end

return M
