local builder = dofile((_G.RANDOMDAY_MOD_ROOT or _G["RandomDay_" .. "RANDOMDAY_MOD_ROOT"] or "RandomDay") .. "/Scripts/ax_profiles/profile_builder.lua")

local overrides = {
    [1] = { id="quiet_intake", display_name="Quiet Intake", experience="Reaction baseline survival", message_line="Keep quiet. Early mistakes are expensive.", dynamic_spawns="standard_pressure", ante_up="standard", lethal_lasers="standard_safety", game_difficulty=2, enemy_accuracy=3, death_penalties=1, multipliers={EnemySpawnRate=0.75, EnemyHealthMultiplier=1.45, EnemyPlayerDamageMultiplier=1.45, DetectionSpeedMultiplier=1.40, PlayerXPGainMultiplier=1.45}, encounter={tier="high", theme="quiet_intake", mixed_encounter_chance=0.03, mixed_encounter_budget=4, mixed_encounter_cooldown=560, allow_multi_group=false}},
    [2] = { id="barricade_protocol", display_name="Barricade Protocol", experience="Build safe, travel carefully", message_line="Base work is authorized. Outside is not forgiving.", dynamic_spawns="quiet_base_safe", ante_up="quiet", lethal_lasers="low_hazard", loot_respawn=true, bonus_perks=7, base_inventory=26, game_difficulty=2, death_penalties=1, multipliers={EnemySpawnRate=0.55, EnemyHealthMultiplier=1.60, EnemyPlayerDamageMultiplier=1.55, DetectionSpeedMultiplier=1.50, PlayerXPGainMultiplier=1.60, ItemDurabilityMultiplier=1.30}, encounter={tier="medium", theme="barricade_protocol", mixed_encounter_chance=0.01, mixed_encounter_budget=3, mixed_encounter_cooldown=800}},
    [3] = { id="contaminated_silence", display_name="Contaminated Silence", experience="Biohazard stealth survival", message_line="Water is risky. Noise is worse.", dynamic_spawns="biohazard_light", ante_up="biohazard", lethal_lasers="standard_safety", game_difficulty=2, enemy_accuracy=3, multipliers={EnemySpawnRate=0.70, EnemyHealthMultiplier=1.70, EnemyPlayerDamageMultiplier=1.55, ThirstSpeedMultiplier=1.45, DetectionSpeedMultiplier=1.55, PlayerXPGainMultiplier=1.65}, encounter={tier="high", theme="contaminated_silence", mixed_encounter_chance=0.04, mixed_encounter_budget=4, mixed_encounter_cooldown=620}},
    [4] = { id="scavengers_debt", display_name="Scavenger's Debt", experience="High reward resource risk", message_line="Loot is richer. So are the consequences.", dynamic_spawns="low_pressure_loot_day", ante_up="loot", lethal_lasers="low_hazard", loot_respawn=true, bonus_perks=5, base_inventory=32, game_difficulty=2, multipliers={EnemySpawnRate=0.65, EnemyHealthMultiplier=1.55, EnemyPlayerDamageMultiplier=1.55, PlayerXPGainMultiplier=1.75, ItemWeightMultiplier=0.70}, encounter={tier="medium", theme="scavengers_debt", mixed_encounter_chance=0.04, mixed_encounter_budget=4, mixed_encounter_cooldown=650}},
    [5] = { id="security_lockdown", display_name="Security Lockdown", experience="Fewer but lethal patrols", message_line="Security patrols are fewer, sharper, and no longer issuing warnings.", dynamic_spawns="security_pressure", ante_up="security", lethal_lasers="high_hazard", game_difficulty=3, enemy_accuracy=4, death_penalties=2, multipliers={EnemySpawnRate=0.80, EnemyHealthMultiplier=1.80, EnemyPlayerDamageMultiplier=1.85, DetectionSpeedMultiplier=2.00, PlayerXPGainMultiplier=1.75}, encounter={tier="extreme", theme="security_lockdown", mixed_encounter_chance=0.06, mixed_encounter_budget=6, mixed_encounter_cooldown=560, allow_multi_group=false}},
    [6] = { id="shelter_advisory", display_name="Shelter Advisory", experience="Weather survival and careful travel", message_line="The forecast is a warning, not a suggestion.", dynamic_spawns="weather_wandering", ante_up="weather", lethal_lasers="electrical_hazard_light", game_difficulty=2, multipliers={EnemySpawnRate=0.70, EnemyHealthMultiplier=1.65, EnemyPlayerDamageMultiplier=1.60, ThirstSpeedMultiplier=1.35, FatigueSpeedMultiplier=1.25, PlayerXPGainMultiplier=1.65}, encounter={tier="high", theme="shelter_advisory", mixed_encounter_chance=0.05, mixed_encounter_budget=5, mixed_encounter_cooldown=620}},
    [7] = { id="lights_out", display_name="Lights Out", experience="Stealth night survival", message_line="Darkness is not cover if you are loud.", dynamic_spawns="night_pressure", ante_up="night", lethal_lasers="night_visible_moderate", game_difficulty=3, enemy_accuracy=4, death_penalties=2, multipliers={EnemySpawnRate=0.70, EnemyHealthMultiplier=1.90, EnemyPlayerDamageMultiplier=1.90, DetectionSpeedMultiplier=2.10, FatigueSpeedMultiplier=1.30, PlayerXPGainMultiplier=1.85}, encounter={tier="extreme", theme="lights_out", mixed_encounter_chance=0.07, mixed_encounter_budget=6, mixed_encounter_cooldown=580}},
    [8] = { id="do_not_linger", display_name="Do Not Linger", experience="Movement survival pressure", message_line="Routes are safer than rooms. Do not linger.", dynamic_spawns="speedrun_pressure", ante_up="speedrun", lethal_lasers="low_to_moderate_hazard", game_difficulty=2, enemy_accuracy=3, multipliers={EnemySpawnRate=0.80, EnemyHealthMultiplier=1.50, EnemyPlayerDamageMultiplier=1.65, DetectionSpeedMultiplier=1.70, PlayerXPGainMultiplier=1.60}, encounter={tier="high", theme="do_not_linger", mixed_encounter_chance=0.06, mixed_encounter_budget=5, mixed_encounter_cooldown=520}},
    [9] = { id="empty_pantry_trial", display_name="Empty Pantry Trial", experience="Severe survival attrition", message_line="Every supply matters. Every fight costs interest.", dynamic_spawns="scarcity_low_frequency", ante_up="scarcity", lethal_lasers="standard_safety", game_difficulty=3, enemy_accuracy=3, death_penalties=2, multipliers={EnemySpawnRate=0.60, EnemyHealthMultiplier=1.75, EnemyPlayerDamageMultiplier=1.75, HungerSpeedMultiplier=1.60, ThirstSpeedMultiplier=1.55, PlayerXPGainMultiplier=1.90}, encounter={tier="high", theme="empty_pantry_trial", mixed_encounter_chance=0.04, mixed_encounter_budget=5, mixed_encounter_cooldown=720}},
    [10] = { id="silent_recovery", display_name="Silent Recovery", experience="Quiet recovery and rebuild", message_line="Recover quietly. The facility is listening.", dynamic_spawns="minimum_pressure", ante_up="recovery", lethal_lasers="disabled_or_low_if_supported", loot_respawn=true, bonus_perks=10, base_inventory=30, game_difficulty=1, multipliers={EnemySpawnRate=0.35, EnemyHealthMultiplier=1.25, EnemyPlayerDamageMultiplier=1.30, PlayerXPGainMultiplier=1.50, ItemWeightMultiplier=0.65}, encounter={tier="very_low", theme="silent_recovery", mixed_encounter_chance=0.00, mixed_encounter_budget=1, mixed_encounter_cooldown=1000}},
    [11] = { id="measured_risk", display_name="Measured Risk", experience="Controlled but punishing encounters", message_line="Training is optional. Consequences are not.", dynamic_spawns="training_targets", ante_up="training", lethal_lasers="training_hazard", game_difficulty=2, enemy_accuracy=2, death_penalties=1, multipliers={EnemySpawnRate=0.60, EnemyHealthMultiplier=1.40, EnemyPlayerDamageMultiplier=1.45, DetectionSpeedMultiplier=1.40, PlayerXPGainMultiplier=1.70}, encounter={tier="medium", theme="measured_risk", mixed_encounter_chance=0.03, mixed_encounter_budget=4, mixed_encounter_cooldown=700}},
    [12] = { id="predator_review", display_name="Predator Review", experience="Elite enemy survival", message_line="The Black Lab sent fewer reviewers. They are worse.", dynamic_spawns="hard_pressure", ante_up="black_lab", lethal_lasers="high_hazard", game_difficulty=3, enemy_accuracy=4, death_penalties=3, multipliers={EnemySpawnRate=0.85, EnemyHealthMultiplier=2.10, EnemyPlayerDamageMultiplier=2.15, DetectionSpeedMultiplier=2.20, PlayerXPGainMultiplier=2.10}, encounter={tier="extreme", theme="predator_review", mixed_encounter_chance=0.10, mixed_encounter_budget=8, mixed_encounter_cooldown=520, allow_multi_group=false}},
    [13] = { id="long_shift_survival", display_name="Long Shift Survival", experience="Slow burn resource drain", message_line="Avoid unnecessary fights. The shift is longer than pride.", dynamic_spawns="slow_attrition", ante_up="attrition", lethal_lasers="standard_safety", game_difficulty=2, death_penalties=2, multipliers={EnemySpawnRate=0.55, EnemyHealthMultiplier=1.70, EnemyPlayerDamageMultiplier=1.75, HungerSpeedMultiplier=1.55, ThirstSpeedMultiplier=1.55, FatigueSpeedMultiplier=1.45, PlayerXPGainMultiplier=1.80}, encounter={tier="high", theme="long_shift_survival", mixed_encounter_chance=0.04, mixed_encounter_budget=5, mixed_encounter_cooldown=780}},
    [14] = { id="false_calm", display_name="False Calm", experience="Quiet high-reward relief with rare danger", message_line="The calm is useful. Trust it only halfway.", dynamic_spawns="relief_day", ante_up="relief", lethal_lasers="disabled_or_low_if_supported", loot_respawn=true, bonus_perks=12, base_inventory=40, game_difficulty=1, multipliers={EnemySpawnRate=0.30, EnemyHealthMultiplier=1.35, EnemyPlayerDamageMultiplier=1.40, PlayerXPGainMultiplier=1.90, ItemWeightMultiplier=0.55}, encounter={tier="low", theme="false_calm", mixed_encounter_chance=0.02, mixed_encounter_budget=3, mixed_encounter_cooldown=900}},
    [15] = { id="seen_first_dead_first", display_name="Seen First, Dead First", experience="Stealth and detection challenge", message_line="If they see you first, the audit is over.", dynamic_spawns="precision_patrols", ante_up="accuracy", lethal_lasers="moderate_hazard", game_difficulty=3, enemy_accuracy=4, death_penalties=2, multipliers={EnemySpawnRate=0.75, EnemyHealthMultiplier=1.70, EnemyPlayerDamageMultiplier=2.00, DetectionSpeedMultiplier=2.30, PlayerXPGainMultiplier=1.95}, encounter={tier="extreme", theme="seen_first_dead_first", mixed_encounter_chance=0.07, mixed_encounter_budget=6, mixed_encounter_cooldown=560}},
    [16] = { id="unapproved_conditions", display_name="Unapproved Conditions", experience="Dangerous anomalies with high rewards", message_line="The variables are hostile. So is the payout.", dynamic_spawns="experimental_mixed", ante_up="experimental", lethal_lasers="weird_cycle_or_standard", game_difficulty=3, enemy_accuracy=3, death_penalties=2, multipliers={EnemySpawnRate=0.85, EnemyHealthMultiplier=1.95, EnemyPlayerDamageMultiplier=1.95, DetectionSpeedMultiplier=1.80, PlayerXPGainMultiplier=2.20}, encounter={tier="extreme", theme="unapproved_conditions", mixed_encounter_chance=0.12, mixed_encounter_budget=8, mixed_encounter_cooldown=500, allow_multi_group=true, max_active_groups=2}},
    [17] = { id="final_evasion_test", display_name="Final Evasion Test", experience="Capstone stealth-survival trial", message_line="Final exam: survive what you cannot afford to fight.", dynamic_spawns="capstone_pressure", ante_up="capstone", lethal_lasers="overcharged_high_hazard", game_difficulty=3, enemy_accuracy=4, death_penalties=3, multipliers={EnemySpawnRate=0.90, EnemyHealthMultiplier=2.30, EnemyPlayerDamageMultiplier=2.30, DetectionSpeedMultiplier=2.40, PlayerXPGainMultiplier=2.50}, encounter={tier="capstone", theme="final_evasion_test", mixed_encounter_chance=0.15, mixed_encounter_budget=10, mixed_encounter_cooldown=440, allow_multi_group=true, max_active_groups=2}},
}

local pack = builder.build("reaction", "REACTION", overrides)
return pack
