return {
    id = "ante_up",
    display_name = "AnteUp",
    required = false,
    compatibility = "Patches AnteUp/scripts/Settings.lua. Lower respawn multiplier means faster respawns in AnteUp. Dev/debug tools are forced off in every profile.",
    config_candidates = {
        "../AnteUp/scripts/Settings.lua",
        "ue4ss/Mods/AnteUp/scripts/Settings.lua",
        "./ue4ss/Mods/AnteUp/scripts/Settings.lua",
        "Mods/AnteUp/scripts/Settings.lua",
        "./Mods/AnteUp/scripts/Settings.lua",
    },
    prepared_profiles = {
        standard = {
            RESPAWN_FREQUENCY_MULTIPLIER=1.0, ANTEVARIANT_FREQUENCY=1.0,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        quiet = {
            RESPAWN_FREQUENCY_MULTIPLIER=1.75, ANTEVARIANT_FREQUENCY=0.4,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        biohazard = {
            RESPAWN_FREQUENCY_MULTIPLIER=0.9, ANTEVARIANT_FREQUENCY=1.2,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        loot = {
            RESPAWN_FREQUENCY_MULTIPLIER=1.35, ANTEVARIANT_FREQUENCY=0.7,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        security = {
            RESPAWN_FREQUENCY_MULTIPLIER=0.8, ANTEVARIANT_FREQUENCY=1.25,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        weather = {
            RESPAWN_FREQUENCY_MULTIPLIER=0.9, ANTEVARIANT_FREQUENCY=1.15,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        night = {
            RESPAWN_FREQUENCY_MULTIPLIER=0.75, ANTEVARIANT_FREQUENCY=1.35,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        speedrun = {
            RESPAWN_FREQUENCY_MULTIPLIER=0.65, ANTEVARIANT_FREQUENCY=1.2,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        scarcity = {
            RESPAWN_FREQUENCY_MULTIPLIER=1.1, ANTEVARIANT_FREQUENCY=1.0,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        recovery = {
            RESPAWN_FREQUENCY_MULTIPLIER=2.5, ANTEVARIANT_FREQUENCY=0.25,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        training = {
            RESPAWN_FREQUENCY_MULTIPLIER=1.4, ANTEVARIANT_FREQUENCY=0.6,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        black_lab = {
            RESPAWN_FREQUENCY_MULTIPLIER=0.55, ANTEVARIANT_FREQUENCY=1.7,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        attrition = {
            RESPAWN_FREQUENCY_MULTIPLIER=1.15, ANTEVARIANT_FREQUENCY=1.1,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        relief = {
            RESPAWN_FREQUENCY_MULTIPLIER=3.0, ANTEVARIANT_FREQUENCY=0.2,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        accuracy = {
            RESPAWN_FREQUENCY_MULTIPLIER=0.75, ANTEVARIANT_FREQUENCY=1.3,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        experimental = {
            RESPAWN_FREQUENCY_MULTIPLIER=0.6, ANTEVARIANT_FREQUENCY=1.8,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
        capstone = {
            RESPAWN_FREQUENCY_MULTIPLIER=0.45, ANTEVARIANT_FREQUENCY=2.0,
            ENABLE_DEV_TOOLS=false, ENABLE_DEBUG_KEYBINDS=false, ENABLE_DEBUG_COMMANDS=false,
            DEBUG_QUEUES=false, DEBUG_DAMAGE_VALUES=false, DEBUG_NPC_ACTIONS=false,
            DEBUG_ATTACHMENTS=false, DEBUG_HOOK_CALLS=false, DEBUG_SHOW_SPAWNERS=false,
            DEBUG_SPAWNER_CD_TIMES=false, DEBUG_BUFF_NAMES=false, DEBUG_TICKACTOR_ACTIONS=false,
            DEBUG_WORLDFLAGS=false,
        },
    }
}
